### ISSUE TITLE
Check MAALI_TOOL_NAME is what we want

### ISSUE THREAD

**Issue by dgrimreaper** [Pawseyops/maali#103]
Please add an environment variable into the cygnet file, such as MAALI_TOOL_NAME_CHECK, where if it is set then to compare it to MAALI_TOOL_NAME that is given on the command line.  This would give a simple concise error message stating that maali was called with the wrong tool name, rather than waiting to cd into the build directory to complain that a directory was not found (which we then work out is because we got the capitalisation wrong).

**Comment by marcodelapierre** [comment]
Daniel mentioned it, Daniel did it ;)
