### ISSUE TITLE
Abort the install for a CUDA-only build that does not have -n on the command line

### ISSUE THREAD

**Issue by dgrimreaper** [Pawseyops/maali#104]
Some software only supports a GPU build.
It would be good to have a variable in the cygnet file, say MAALI_CUDA_BUILD_ONLY, and if this is set to 1 then abort the install if MAALI_CUDA_BUILD was not set to 1 via the command line -n flag.  This would mean we don't have to test for it further down in the cygnet file, making the cygnet files cleaner.

**Comment by marcodelapierre** [comment]
Daniel mentioned it, Daniel did it ;)
