### ISSUE TITLE
For Python modulefiles, do not load default Python if not Python module is loaded - user must do it explicitly.

### ISSUE THREAD

**Issue by dipietrantonio** [Pawseyops/maali#111]
It has emerged during the supercomputing meetings, and I agree, that users must explicitly load a Python interpreter before using a Python module. Not doing so should result in a error message, e.g., "Python interpreter not loaded."

**Comment by marcodelapierre** [comment]
Had a nice coffee chat with @Halolegend94 , suggested implementing a variable switch in maali to disable "module load python" during module creation. (needs to take into account both cases of python as COMPILER and PREREQ)

**Comment by dipietrantonio** [comment]
this is done
