### ISSUE TITLE
Compiler variables in Cray modulefiles

### ISSUE THREAD

**Issue by dgrimreaper** [Pawseyops/maali#26]
Have the following feedback.  It only affects maali on Cray, due to Cray modules for the compilers not setting the relevant environment variables that we need.

Hi,

When I unload multiple modules built with maali I get the following problem for the second unload:
  cfitsio/3370(48):ERROR:102: Tcl command execution failed: setenv       MAALI_CFITSIO_HOME /pawsey/cle52up04/devel/$env(MAALI_LOADED_PRGENV)/$env(CRAYOS_VERSION)/$env(COMPILER)/$env(COMPILER_VER)/$env(CRAY_CPU_TARGET)/cfitsio/3370

It happens because those environment variables get unset during the first unload.

To reproduce:
  $ module swap PrgEnv-cray PrgEnv-gnu
  $ module load cfitsio/3370
  $ module load gsl/1.16
  $ module unload gsl
  $ module unload cfitsio/3370

The problem seems to happen because the following code will unset those environment variables with the first unload:
if { [is-loaded PrgEnv-gnu] } {
     setenv MAALI_LOADED_PRGENV PrgEnv-gnu
     setenv COMPILER            gcc
     setenv COMPILER_VER        $env(GCC_VERSION)
}

The following code seems better behaved:
if { [is-loaded PrgEnv-gnu] } {
    if { [module-info mode load] || [module-info mode switch] } {
       setenv MAALI_LOADED_PRGENV PrgEnv-gnu
       setenv COMPILER            gcc
       setenv COMPILER_VER        $env(GCC_VERSION)
    } else {
       unsetenv MAALI_LOADED_PRGENV PrgEnv-gnu
       unsetenv COMPILER            gcc
       unsetenv COMPILER_VER        $env(GCC_VERSION)
     }
}
It will leave the variables in the environment after everything is unloaded, but I think otherwise it is good.

**Comment by schibeci** [comment]
Fixed in 1.2.6

**Comment by dgrimreaper** [comment]
This fix using unsetenv produces errors if a different PrgEnv is loaded to what is being tested for, since the "else" is too generic and the $env() will fail.  Having the test repeated for PrgEnv-cray/PrgEnv-gnu/PrgEnv-intel in the same modulefile will always result in an error.

**Comment by dgrimreaper** [comment]
This seems better.  Separated out the setenv/unsetenv from the various PrgEnv testing.

if { [module-info mode load] || [module-info mode switch] || [module-info mode remove] } {
if { [ is-loaded PrgEnv-cray ] } {
  set MAALI_LOADED_PRGENV PrgEnv-cray
  set COMPILER            cce
  set COMPILER_VER        $env(CRAY_CC_VERSION)
}
if { [ is-loaded PrgEnv-gnu ] } {
  set MAALI_LOADED_PRGENV PrgEnv-gnu
  set COMPILER            gcc
  set COMPILER_VER        $env(GCC_VERSION)
}
if { [ is-loaded PrgEnv-intel ] } {
  set MAALI_LOADED_PRGENV PrgEnv-intel
  set COMPILER            intel
  set COMPILER_VER        $env(INTEL_VERSION)
}
}

if { [ info exists MAALI_LOADED_PRGENV ] } {
  if { [module-info mode load] || [module-info mode switch] } {
    setenv MAALI_LOADED_PRGENV $MAALI_LOADED_PRGENV
    setenv COMPILER $COMPILER
    setenv COMPILER_VER $COMPILER_VER
  } elseif { [module-info mode remove] } {
    unsetenv MAALI_LOADED_PRGENV $MAALI_LOADED_PRGENV
    unsetenv COMPILER $COMPILER
    unsetenv COMPILER_VER $COMPILER_VER
  }
}

**Comment by schibeci** [comment]
Will be fixed in 1.4 (for TCL not LUA)
