### ISSUE TITLE
RHEL 7.3 not supported

### ISSUE THREAD

**Issue by zqmuser** [Pawseyops/maali#27]
We decided to give Maali a test drive at the Alabama Supercomputer Center, but didn't get very far.  

We started by downloading the 1.2.6 release tar file.  The install directions said to clone the development tip from github, but as a we are a production environment our policy is to use stable releases not development builds.

The README.md in the downloaded tar file and the installation page on the github wiki had different commands for running the self installer.  Since the README.md file appeared to be newer, we tried running that one.  The result we got is as follows.

MAALI_MODULE_SET_MAALI_DEFAULT_COMPILERS='gcc/6.1.0 intel/17.0.4 pgi/17.5' ./maali -t maali -v 1.2.6
Your Operating System is not support by maali, please lodge a ticket at https://github/Pawseyops/maali

This was done using RHEL 7.3 on an SGI Ultraviolet 2000.  Our other cluster uses CentOS 7.3

**Comment by schibeci** [comment]
Can you try downloading 1.2.8?

I should have support for RHEL 7 and CentOS 7

**Comment by zqmuser** [comment]
Version 1.2.8 seems to have fixed this issue.  I'll leave it up to the developers if they want to do any more before closing this ticket.
