### ISSUE TITLE
-l argument to maali gives errors

### ISSUE THREAD

**Issue by zqmuser** [Pawseyops/maali#31]
I tried installing Maali on RHEL 7.3.  I edited the maali script to set MAALI_ROOT per our system config, then ran the command

MAALI_MODULE_SET_MAALI_DEFAULT_COMPILERS='gcc/6.1.0 intel/17.0.4 pgi/17.5' ./maali -t maali -v 1.2.8 -l

"maali -h" shows -l as a valid option for generating Lua module files, but when I include it I get the error.

./maali: line 2105: maali_module_lua: command not found

**Comment by schibeci** [comment]
The lua module generating is currently being tested out at pawsey.

You should be able to test it out using maali 1.3.6, but there is still some work to be done.

**Comment by dgrimreaper** [comment]
LUA modules are fixed, working fine in maali/1.5x
