### ISSUE TITLE
CRAYOS_VERSION not defined

### ISSUE THREAD

**Issue by mshaikh786** [Pawseyops/maali#42]
With CLE6 the variable CRAYOS_VERSION is not defined in new CDTs. Maali modulefiles rely on this variable to expand the install path. Suggestion is to set it in the maali script itself or capture it while creating the new modulefiles for the tool by using the config file used to build that tool/version.

**Comment by schibeci** [comment]
This should be fixed with maali 1.5b1 on galaxy

**Comment by dgrimreaper** [comment]
Fixed
