### ISSUE TITLE
MPI in module paths also for TCL?

### ISSUE THREAD

**Issue by marcodelapierre** [Pawseyops/maali#65]
The MPI loop has been added in general, so it can work for both TCL and LUA modules, but the install paths have been changed to include MPI name/ver only for LUA.
I imagine this has been done with support for multiple MPI on Zeus in mind. However, I am wondering whether in the future this could lead to errors if multiple MPI is made available on machines were TCL is used. 
Would it be harmful to add MPI in paths also in the case of TCL modules?

**Comment by schibeci** [comment]
We'll add MPI to the TCL module generation once it has been sorted out for LUA.

Need to test it out on Zeus first.

**Comment by marcodelapierre** [comment]
Implemented in #98
