### ISSUE TITLE
Option to download cygnet file and do nothing else

### ISSUE THREAD

**Issue by dgrimreaper** [Pawseyops/maali#8]
Hi,

please implement a command line option to download the cygnet file and then exit.  This is so that users can download the correct cygnet file for their OS before doing customisations to it and then compiling with Maali.

Thanks,
Daniel.

**Comment by marcodelapierre** [comment]
If a user needs to edit the cygnet on their own, I'd rather advise them to `git clone` the entire `maali-cygnet` repo, and start from there. 
It's a simple command to advise, which enables them straight away to use version control on their edits.
